//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loginshopping
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int product_code { get; set; }
        public string product_name { get; set; }
        public Nullable<int> price { get; set; }
    }
}
